/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diviso.graeshoppe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8430915424350257218L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"com.diviso.graeshoppe.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"]},{\"name\":\"reference\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"image\",\"type\":\"bytes\",\"default\":\"ÿ\"},{\"name\":\"imageLink\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"contact\",\"type\":{\"type\":\"record\",\"name\":\"Contact\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"]},{\"name\":\"mobileNumber\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"phoneCode\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"telephone\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"email\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<Customer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Customer to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Customer from a ByteBuffer. */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.String reference;
  @Deprecated public java.lang.String name;
  @Deprecated public java.nio.ByteBuffer image;
  @Deprecated public java.lang.String imageLink;
  @Deprecated public java.lang.String status;
  @Deprecated public com.diviso.graeshoppe.avro.Contact contact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param reference The new value for reference
   * @param name The new value for name
   * @param image The new value for image
   * @param imageLink The new value for imageLink
   * @param status The new value for status
   * @param contact The new value for contact
   */
  public Customer(java.lang.Long id, java.lang.String reference, java.lang.String name, java.nio.ByteBuffer image, java.lang.String imageLink, java.lang.String status, com.diviso.graeshoppe.avro.Contact contact) {
    this.id = id;
    this.reference = reference;
    this.name = name;
    this.image = image;
    this.imageLink = imageLink;
    this.status = status;
    this.contact = contact;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return reference;
    case 2: return name;
    case 3: return image;
    case 4: return imageLink;
    case 5: return status;
    case 6: return contact;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: reference = (java.lang.String)value$; break;
    case 2: name = (java.lang.String)value$; break;
    case 3: image = (java.nio.ByteBuffer)value$; break;
    case 4: imageLink = (java.lang.String)value$; break;
    case 5: status = (java.lang.String)value$; break;
    case 6: contact = (com.diviso.graeshoppe.avro.Contact)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'reference' field.
   * @return The value of the 'reference' field.
   */
  public java.lang.String getReference() {
    return reference;
  }

  /**
   * Sets the value of the 'reference' field.
   * @param value the value to set.
   */
  public void setReference(java.lang.String value) {
    this.reference = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'image' field.
   * @return The value of the 'image' field.
   */
  public java.nio.ByteBuffer getImage() {
    return image;
  }

  /**
   * Sets the value of the 'image' field.
   * @param value the value to set.
   */
  public void setImage(java.nio.ByteBuffer value) {
    this.image = value;
  }

  /**
   * Gets the value of the 'imageLink' field.
   * @return The value of the 'imageLink' field.
   */
  public java.lang.String getImageLink() {
    return imageLink;
  }

  /**
   * Sets the value of the 'imageLink' field.
   * @param value the value to set.
   */
  public void setImageLink(java.lang.String value) {
    this.imageLink = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'contact' field.
   * @return The value of the 'contact' field.
   */
  public com.diviso.graeshoppe.avro.Contact getContact() {
    return contact;
  }

  /**
   * Sets the value of the 'contact' field.
   * @param value the value to set.
   */
  public void setContact(com.diviso.graeshoppe.avro.Contact value) {
    this.contact = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.Customer.Builder newBuilder() {
    return new com.diviso.graeshoppe.avro.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.Customer.Builder newBuilder(com.diviso.graeshoppe.avro.Customer.Builder other) {
    return new com.diviso.graeshoppe.avro.Customer.Builder(other);
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.Customer.Builder newBuilder(com.diviso.graeshoppe.avro.Customer other) {
    return new com.diviso.graeshoppe.avro.Customer.Builder(other);
  }

  /**
   * RecordBuilder for Customer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private java.lang.Long id;
    private java.lang.String reference;
    private java.lang.String name;
    private java.nio.ByteBuffer image;
    private java.lang.String imageLink;
    private java.lang.String status;
    private com.diviso.graeshoppe.avro.Contact contact;
    private com.diviso.graeshoppe.avro.Contact.Builder contactBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reference)) {
        this.reference = data().deepCopy(fields()[1].schema(), other.reference);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.image)) {
        this.image = data().deepCopy(fields()[3].schema(), other.image);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.imageLink)) {
        this.imageLink = data().deepCopy(fields()[4].schema(), other.imageLink);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.contact)) {
        this.contact = data().deepCopy(fields()[6].schema(), other.contact);
        fieldSetFlags()[6] = true;
      }
      if (other.hasContactBuilder()) {
        this.contactBuilder = com.diviso.graeshoppe.avro.Contact.newBuilder(other.getContactBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.Customer other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reference)) {
        this.reference = data().deepCopy(fields()[1].schema(), other.reference);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.image)) {
        this.image = data().deepCopy(fields()[3].schema(), other.image);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.imageLink)) {
        this.imageLink = data().deepCopy(fields()[4].schema(), other.imageLink);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.contact)) {
        this.contact = data().deepCopy(fields()[6].schema(), other.contact);
        fieldSetFlags()[6] = true;
      }
      this.contactBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference' field.
      * @return The value.
      */
    public java.lang.String getReference() {
      return reference;
    }

    /**
      * Sets the value of the 'reference' field.
      * @param value The value of 'reference'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setReference(java.lang.String value) {
      validate(fields()[1], value);
      this.reference = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reference' field has been set.
      * @return True if the 'reference' field has been set, false otherwise.
      */
    public boolean hasReference() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reference' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearReference() {
      reference = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'image' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getImage() {
      return image;
    }

    /**
      * Sets the value of the 'image' field.
      * @param value The value of 'image'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setImage(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.image = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'image' field has been set.
      * @return True if the 'image' field has been set, false otherwise.
      */
    public boolean hasImage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'image' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearImage() {
      image = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'imageLink' field.
      * @return The value.
      */
    public java.lang.String getImageLink() {
      return imageLink;
    }

    /**
      * Sets the value of the 'imageLink' field.
      * @param value The value of 'imageLink'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setImageLink(java.lang.String value) {
      validate(fields()[4], value);
      this.imageLink = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'imageLink' field has been set.
      * @return True if the 'imageLink' field has been set, false otherwise.
      */
    public boolean hasImageLink() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'imageLink' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearImageLink() {
      imageLink = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setStatus(java.lang.String value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'contact' field.
      * @return The value.
      */
    public com.diviso.graeshoppe.avro.Contact getContact() {
      return contact;
    }

    /**
      * Sets the value of the 'contact' field.
      * @param value The value of 'contact'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder setContact(com.diviso.graeshoppe.avro.Contact value) {
      validate(fields()[6], value);
      this.contactBuilder = null;
      this.contact = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'contact' field has been set.
      * @return True if the 'contact' field has been set, false otherwise.
      */
    public boolean hasContact() {
      return fieldSetFlags()[6];
    }

    /**
     * Gets the Builder instance for the 'contact' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.diviso.graeshoppe.avro.Contact.Builder getContactBuilder() {
      if (contactBuilder == null) {
        if (hasContact()) {
          setContactBuilder(com.diviso.graeshoppe.avro.Contact.newBuilder(contact));
        } else {
          setContactBuilder(com.diviso.graeshoppe.avro.Contact.newBuilder());
        }
      }
      return contactBuilder;
    }

    /**
     * Sets the Builder instance for the 'contact' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.diviso.graeshoppe.avro.Customer.Builder setContactBuilder(com.diviso.graeshoppe.avro.Contact.Builder value) {
      clearContact();
      contactBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'contact' field has an active Builder instance
     * @return True if the 'contact' field has an active Builder instance
     */
    public boolean hasContactBuilder() {
      return contactBuilder != null;
    }

    /**
      * Clears the value of the 'contact' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.Customer.Builder clearContact() {
      contact = null;
      contactBuilder = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.reference = fieldSetFlags()[1] ? this.reference : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.image = fieldSetFlags()[3] ? this.image : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        record.imageLink = fieldSetFlags()[4] ? this.imageLink : (java.lang.String) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.String) defaultValue(fields()[5]);
        if (contactBuilder != null) {
          record.contact = this.contactBuilder.build();
        } else {
          record.contact = fieldSetFlags()[6] ? this.contact : (com.diviso.graeshoppe.avro.Contact) defaultValue(fields()[6]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
