/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diviso.graeshoppe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FavouriteStore extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6231343878474255943L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FavouriteStore\",\"namespace\":\"com.diviso.graeshoppe.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"]},{\"name\":\"storeId\",\"type\":[\"null\",\"long\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FavouriteStore> ENCODER =
      new BinaryMessageEncoder<FavouriteStore>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FavouriteStore> DECODER =
      new BinaryMessageDecoder<FavouriteStore>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FavouriteStore> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FavouriteStore> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FavouriteStore>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FavouriteStore to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FavouriteStore from a ByteBuffer. */
  public static FavouriteStore fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.Long storeId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FavouriteStore() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param storeId The new value for storeId
   */
  public FavouriteStore(java.lang.Long id, java.lang.Long storeId) {
    this.id = id;
    this.storeId = storeId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return storeId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: storeId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'storeId' field.
   * @return The value of the 'storeId' field.
   */
  public java.lang.Long getStoreId() {
    return storeId;
  }

  /**
   * Sets the value of the 'storeId' field.
   * @param value the value to set.
   */
  public void setStoreId(java.lang.Long value) {
    this.storeId = value;
  }

  /**
   * Creates a new FavouriteStore RecordBuilder.
   * @return A new FavouriteStore RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.FavouriteStore.Builder newBuilder() {
    return new com.diviso.graeshoppe.avro.FavouriteStore.Builder();
  }

  /**
   * Creates a new FavouriteStore RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FavouriteStore RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.FavouriteStore.Builder newBuilder(com.diviso.graeshoppe.avro.FavouriteStore.Builder other) {
    return new com.diviso.graeshoppe.avro.FavouriteStore.Builder(other);
  }

  /**
   * Creates a new FavouriteStore RecordBuilder by copying an existing FavouriteStore instance.
   * @param other The existing instance to copy.
   * @return A new FavouriteStore RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.FavouriteStore.Builder newBuilder(com.diviso.graeshoppe.avro.FavouriteStore other) {
    return new com.diviso.graeshoppe.avro.FavouriteStore.Builder(other);
  }

  /**
   * RecordBuilder for FavouriteStore instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FavouriteStore>
    implements org.apache.avro.data.RecordBuilder<FavouriteStore> {

    private java.lang.Long id;
    private java.lang.Long storeId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.FavouriteStore.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.storeId)) {
        this.storeId = data().deepCopy(fields()[1].schema(), other.storeId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FavouriteStore instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.FavouriteStore other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.storeId)) {
        this.storeId = data().deepCopy(fields()[1].schema(), other.storeId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.FavouriteStore.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.FavouriteStore.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeId' field.
      * @return The value.
      */
    public java.lang.Long getStoreId() {
      return storeId;
    }

    /**
      * Sets the value of the 'storeId' field.
      * @param value The value of 'storeId'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.FavouriteStore.Builder setStoreId(java.lang.Long value) {
      validate(fields()[1], value);
      this.storeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'storeId' field has been set.
      * @return True if the 'storeId' field has been set, false otherwise.
      */
    public boolean hasStoreId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'storeId' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.FavouriteStore.Builder clearStoreId() {
      storeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FavouriteStore build() {
      try {
        FavouriteStore record = new FavouriteStore();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.storeId = fieldSetFlags()[1] ? this.storeId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FavouriteStore>
    WRITER$ = (org.apache.avro.io.DatumWriter<FavouriteStore>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FavouriteStore>
    READER$ = (org.apache.avro.io.DatumReader<FavouriteStore>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
